name: Pipeline CI e CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o código
        uses: actions/checkout@v3
      - name: Rodando Testes de CI
        run: echo "Testes de Integração aprovados com sucesso!"

  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o código
        uses: actions/checkout@v3
      - name: Simulando o CD e Docker
        run: echo "Deploy simulado com sucesso! Imagem pronta."
